### PR TITLE
fix: improve comment cleanup regex

### LINKED ISSUE #308: Some comments are not cleaned up during import
**Description**

When importing https://www.wilson.com/en-us/blog/basketball/events/wilson-takes-paris-storm-recap-nba-paris-game-2024, most of the comments are not cleaned up.

Excerpt:

```
<!-- .l-main region -->

<!-- Tabs-->

# Wilson Takes Paris by Storm: Recap of NBA Paris Game 2024

Experience the electrifying highlights of Wilson's presence at the NBA Paris Game 2024, as we take you on a journey through the heart of Paris.

![Wilson's Bonded by Ball 2v2 Basketball Tournament][image0]

In the heart of Paris, Wilson Basketball brought the city to life with its genuine "Bonded by Ball" campaign, capturing the authentic Parisian vibe, strengthening the connection with the local basketball community, and celebrating the true spirit of the sport. As the Official Basketball of the NBA, Wilson played a significant role in the NBA Paris Game 2024, hosting various events and activations around the city. Let's dive into the exciting moments and community engagement that made this international basketball spectacle unforgettable.
[...]
```

**To Reproduce**
Import https://www.wilson.com/en-us/blog/basketball/events/wilson-takes-paris-storm-recap-nba-paris-game-2024 with default script (or no script)
=> Notice the remaining comments in the import result

**Expected behavior**
All comments should be removed automatically

### PR DESCRIPTION
**Pull request by catalan-adobe**
Fixes #308.

### CODE REVIEW

**Review by kptdobe — CHANGES_REQUESTED** [review]
Would be great to add corresponding tests ?

**Comment by catalan-adobe** [comment]
> Would be great to add corresponding tests ?

True true :) ! Done in [6b05e99](https://github.com/adobe/helix-importer/pull/309/commits/6b05e99b82146a1d9c13acd7c8c3f54025d7d2e2)

**Review by kptdobe — APPROVED** [review]
Thanks!

**Review by alexcarol — APPROVED** [review]
Looking good!

**Review by kptdobe — APPROVED** [review]

**Pull request merged**
